# Generated by Django 2.2.3 on 2019-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySimpleModel',
            fields=[
                ('emp_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('emp_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_post', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_salary', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
